# Inspired by Godot's GLSL header generator
# We take the source of a GLSL script and simply insert it into a header

import sys
import os

in_path = sys.argv[1]
out_path = sys.argv[2]

source = ""

out_name = os.path.basename(out_path)

source_name = os.path.basename(in_path)
source_name = os.path.splitext(source_name)[0]
source_name = source_name.replace(".", "_")

print(f"Generating resource header '{out_name}'...")
print(f"\tInput: {sys.argv[1]}")
print(f"\tOutput: {sys.argv[2]}")

with open(sys.argv[1], "rb") as src_file:
    source = src_file.read()

with open(sys.argv[2], "w") as out_file:
    out_file.write("//\n")
    out_file.write("// Generated by gen_resource_header.py\n")
    out_file.write("//\n\n")

    source_repr = source
    #source_repr = source_repr.removeprefix("'").removesuffix("'")

    out_file.write(f"const unsigned char {source_name.upper()}_CONTENTS[] = {{")

    i = 0
    for b in source:
        if i > 0:
            out_file.write(', ')

        if i % 16 == 0:
            out_file.write('\n\t')

        out_file.write(f'0x{b:02X}')
        i += 1

    out_file.write("\n};")
